name: Horusec

on: [push, pull_request]

jobs:
  horusec:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Horusec
        run: curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/master/scripts/install.sh | bash
      - name: Run Horusec
        run: horusec start -p .
