name: Horusec Scan

on:
  push:
    branches: [main]

jobs:
  horusec-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Horusec
        uses: docker://horuszup/horusec-cli:v2.4.2
        with:
          args: |
            horusec start -p /github/workspace -e "json" -o "/github/workspace/horusec-result.json" -x ".horusec/config.json"
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        id: horusec
      - name: Print output
        run: echo "${{ steps.horusec.outputs.result }}"
